objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>Co-{0000}</displayFormat>
        <label>Course Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>St-{0000}</displayFormat>
        <label>Student Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CourseHandler.cls
public class CourseHandler 
{
    public static void DelChildRec(Map<Id,Course__c> oldMap,Map<Id,Course__c> newMap)
    {
        List<Id> courseIds=new List<Id>();
        for(Id key :oldMap.keySet()){
            Course__C old=oldMap.get(key);
            Course__c newCourse=newMap.get(key);
            if(old.Status__c!='InActive' && newCourse.Status__c=='InActive')
            {
                courseIds.add(key);
            }	
        }	
        List<Student__c> stds=[select id from Student__C where Course__c IN :courseIds];
        delete stds;
    }
}